### PR TITLE
Map mission coupling

### PR DESCRIPTION
**Pull request by BartKieviet**
- Routeplanner updates now on nav when changed/activated on. nav
  - And with css instead of style change
- Shows red square where missions are going to on minimap.
- non-prem WH clean now updates from jobs page.
  - not yet from bulletin board

@Tsunder  please have a look.

### CODE REVIEW

**Comment by Tsunder** [comment]
1. if a wormhole is on the highlighted path, it uh, does this 
image

The css looks "okay" though? 
`<td style="background-image:url(&quot;//static.pardus.at/img/stdhq/backgrounds/energy6.png&quot;);" id="tdNavField86" class="navWormhole sweetener-routeplanner"><a onclick="navAjax(307773)"></a></td>`

2. the existing saved path functionality where it shows the path on the minimap, no longer seems to work.

3. mission target doesn't light up until the minimap is updated. The first time the pilot enters the sector with a targetted mission, the square in the minimap is not lit. It updates when the pilot navs (moves/updates the minimap?). (Then it seems to be OK, even after leaving and returning to sector)

4. I think pilot's current tile should be included in highlights, as it's part of any "path" the pilot takes. (this is actually a (reported i think) bug w/ the minimap pathfinder anyway)

5. I do not have access to test WH cleaning.

**Comment by BartKieviet** [comment]
1. I see my other apps had an extra CSS line that stopped me from finding the bug, fixed in 137a22e97504e501af45bed4a637e8977b02b3b2.
2. If you click on the map, it runs the configuration script, renewing the whole page. Therefore, the saved path variable used is again cleared. Since we store it it can be easily recalled.
3. That's because the `minimap` variable is `undefined` when coming directly from a nav click/refresh. I don't know why, because it does show it. This is most likely related to your `navtable` oddity. 
4. I see it's only not highlighted when one's on a building, but it is when on a clear tile. Note: this is when moving, when refreshing nav, the highlight disappears. I think because the tile has no `a` tag with `onclick` attribute, so it's not found by the function. We should manually check if our current tile is in the list.
5. Lose comp for science! 😜

**Comment by BartKieviet** [comment]
ddd53cd32314964cb82f4db051e875923e51e02b fixes #41

**Comment by Tsunder** [comment]
the new colour looks like asteroids colour >_>

seems to be relatively in order otherwise
3. maybe one of those "race conditions" and "load order" people talk about
4. a manual check at the end for our location being on it would be yeah.

**Comment by BartKieviet** [comment]
image
It's a lot more poo-colored than the grey asteroids, I think.

**Comment by Tsunder** [comment]
That's quite the colourful description of a pilot's path. 🤣 

Upon setting a path, the mouse/event drops the path details text (APs usage / POI info)

**Pull request merged**
