### PR TITLE
Nav coords

### PR DESCRIPTION
**Pull request by Tsunder**

### CODE REVIEW

**Comment by Tsunder** [comment]
adds #52 
looks like 
image
works for all tile sizes and nav grid sizes

**Comment by Tsunder** [comment]
probably massively increases nav load time though. ~~just like everything else in sweetener~~

**Comment by BartKieviet** [comment]
The above Nav and below nav row do not align

**Comment by Tsunder** [comment]
b329aa1 alignmenting
64x64 image
96x96 image

**Comment by Tsunder** [comment]
@BartKieviet seems good to go to me, you?

**Pull request merged**
