### PR TITLE
Newbie pull request

### PR DESCRIPTION
**Pull request by Sei-lus**
Fix for:
#97 , #98 , #99 , #100 . #101 , #17 , #14 
"consistent text in drug/stim usage messages" #17
Drugs message is now consistent with the Stim Message.

Added a Title + Column Separator of "Display Missions" on Nav Screen
Justification: As a new player, I had no idea what each column really meant until I read the code.
Also added specific IDs to better CSS the table on Stylus.

Quality of Life change to clock order:
Drug and Stim clocks are now side by side.
GMT renamed to UTC because I consider GMT really outdated. People need to get on the new terms.
Put Server Reset and UTC as the last clocks since they happen once a day.
Removed Repair Quicklink and Trade quicklink since Pardus includes it nowadays.

#93 Warning. I changed the timer to 0,29,3,0 in nav.js since I care more about Artemis and don't use drugs on the others 2. You may not want to merge that specific line.

First time using GitHub, hope I helped somehow.
[Pull Request.zip](https://github.com/Tsunder/Pardus-Sweetener/files/4638518/Pull.Request.zip)

### CODE REVIEW

**Comment by Tsunder** [comment]
Thanks for the PR @Sei-lus !
Did you mean to add some more changes? There appear to be no changes by you.

**Comment by Sei-lus** [comment]
I added a Zip with changes I made... To be honest I thought I had to add the zip and it would show what was changed.

There are changes to nav.js, clock.js, options.html, options.js, bg.js, and maybe the manifest.json...

**Comment by Sei-lus** [comment]
#30 (https://github.com/Tsunder/Pardus-Sweetener/issues/30)

Is fixed (or was fixed before) in this zip:
[Pardus Sweetner Artemis.zip](https://github.com/Tsunder/Pardus-Sweetener/files/4640764/Pardus.Sweetner.Artemis.zip)

I changed the name of the addon to "Sweetner Artemis" and the version to test privately in Mozilla. But the fact it says Artemis is a good indicator that this also has the drug timer changed.

Teach me how to properly use pull requests that compare previous changes if you can.

**Comment by Tsunder** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Pull request closed without merging**
